### ISSUE TITLE
[Bug]0.8.1 undefined reference to `Adafruit_USBD_MIDI::Adafruit_USBD_MIDI()

### ISSUE THREAD

**Issue by deladriere** [adafruit/Adafruit_TinyUSB_Arduino#43]
I receive this error while compiling with Platformio
I was working fine with the 0.6.0 version
Here is my platformio ini

[env:adafruit_feather_m0]
platform = atmelsam
board = adafruit_feather_m0
build_flags = -D USE_TINYUSB
framework = arduino
lib_deps =
    Adafruit TinyUSB Library@0.8.1
    MIDI Library@4.3.1
    SSD1306Ascii@1.2.4
monitor_speed = 115200

**Comment by deladriere** [comment]
@ivankravets can you check this too ?

**Comment by hathach** [comment]
Can you confirm this issue on Arduino with latest adafruit samd bsp ?

**Comment by deladriere** [comment]
@hathach I am running this with  platformio and it is still on the Adafruit SAMD Adafruit Core  1.5.3
could this be the reason?

**Comment by hathach** [comment]
Close since the issue is not reproducible on Arduino IDE, and not bug of this repo
