### ISSUE TITLE
"midi_test" does not compile for ESP32S3

### ISSUE THREAD

**Issue by jhsa** [adafruit/Adafruit_TinyUSB_Arduino#420]
### Operating System

Linux

### Arduino IDE version

Arduino IDE 2.3.2

### Board

ESP32S3 Dev Module

### ArduinoCore version

2.0.13

### TinyUSB Library version

Latest 3.1.4

### Sketch as ATTACHED TXT

Examples/MIDI/midi_test

### Compiled Log as ATTACHED TXT

`
c:\Users\Joao\Documents\Arduino\libraries\Adafruit_TinyUSB_Library\src\device\usbd.c:109:10: error: 'usbd_class_driver_t' {aka 'const struct <anonymous>'} has no member named 'deinit'; did you mean 'init'?
         .deinit           = cdcd_deinit,
          ^~~~~~
          init
c:\Users\Joao\Documents\Arduino\libraries\Adafruit_TinyUSB_Library\src\device\usbd.c:109:29: error: 'cdcd_deinit' undeclared here (not in a function); did you mean 'dcd_deinit'?
         .deinit           = cdcd_deinit,
                             ^~~~~~~~~~~
                             dcd_deinit
c:\Users\Joao\Documents\Arduino\libraries\Adafruit_TinyUSB_Library\src\device\usbd.c:122:10: error: 'usbd_class_driver_t' {aka 'const struct <anonymous>'} has no member named 'deinit'; did you mean 'init'?
         .deinit           = NULL,
          ^~~~~~
          init
c:\Users\Joao\Documents\Arduino\libraries\Adafruit_TinyUSB_Library\src\device\usbd.c:135:10: error: 'usbd_class_driver_t' {aka 'const struct <anonymous>'} has no member named 'deinit'; did you mean 'init'?
         .deinit           = hidd_deinit,
          ^~~~~~
          init
c:\Users\Joao\Documents\Arduino\libraries\Adafruit_TinyUSB_Library\src\device\usbd.c:135:29: error: 'hidd_deinit' undeclared here (not in a function); did you mean 'hidd_init'?
         .deinit           = hidd_deinit,
                             ^~~~~~~~~~~
                             hidd_init
c:\Users\Joao\Documents\Arduino\libraries\Adafruit_TinyUSB_Library\src\device\usbd.c:161:10: error: 'usbd_class_driver_t' {aka 'const struct <anonymous>'} has no member named 'deinit'; did you mean 'init'?
         .deinit           = videod_deinit,
          ^~~~~~
          init
c:\Users\Joao\Documents\Arduino\libraries\Adafruit_TinyUSB_Library\src\device\usbd.c:161:29: error: 'videod_deinit' undeclared here (not in a function); did you mean 'videod_init'?
         .deinit           = videod_deinit,
                             ^~~~~~~~~~~~~
                             videod_init
c:\Users\Joao\Documents\Arduino\libraries\Adafruit_TinyUSB_Library\src\device\usbd.c:174:10: error: 'usbd_class_driver_t' {aka 'const struct <anonymous>'} has no member named 'deinit'; did you mean 'init'?
         .deinit           = midid_deinit,
          ^~~~~~
          init
c:\Users\Joao\Documents\Arduino\libraries\Adafruit_TinyUSB_Library\src\device\usbd.c:174:29: error: 'midid_deinit' undeclared here (not in a function); did you mean 'midid_init'?
         .deinit           = midid_deinit,
                             ^~~~~~~~~~~~
                             midid_init
c:\Users\Joao\Documents\Arduino\libraries\Adafruit_TinyUSB_Library\src\device\usbd.c:187:10: error: 'usbd_class_driver_t' {aka 'const struct <anonymous>'} has no member named 'deinit'; did you mean 'init'?
         .deinit           = vendord_deinit,
          ^~~~~~
          init
c:\Users\Joao\Documents\Arduino\libraries\Adafruit_TinyUSB_Library\src\device\usbd.c:187:29: error: 'vendord_deinit' undeclared here (not in a function); did you mean 'vendord_init'?
         .deinit           = vendord_deinit,
                             ^~~~~~~~~~~~~~
                             vendord_init
c:\Users\Joao\Documents\Arduino\libraries\Adafruit_TinyUSB_Library\src\device\usbd.c:213:10: error: 'usbd_class_driver_t' {aka 'const struct <anonymous>'} has no member named 'deinit'; did you mean 'init'?
         .deinit           = dfu_rtd_deinit,
          ^~~~~~
          init
c:\Users\Joao\Documents\Arduino\libraries\Adafruit_TinyUSB_Library\src\device\usbd.c:213:29: error: 'dfu_rtd_deinit' undeclared here (not in a function); did you mean 'dfu_rtd_init'?
         .deinit           = dfu_rtd_deinit,
                             ^~~~~~~~~~~~~~
                             dfu_rtd_init
c:\Users\Joao\Documents\Arduino\libraries\Adafruit_TinyUSB_Library\src\device\usbd.c:226:10: error: 'usbd_class_driver_t' {aka 'const struct <anonymous>'} has no member named 'deinit'; did you mean 'init'?
         .deinit           = dfu_moded_deinit,
          ^~~~~~
          init
c:\Users\Joao\Documents\Arduino\libraries\Adafruit_TinyUSB_Library\src\device\usbd.c:226:29: error: 'dfu_moded_deinit' undeclared here (not in a function); did you mean 'dfu_moded_init'?
         .deinit           = dfu_moded_deinit,
                             ^~~~~~~~~~~~~~~~
                             dfu_moded_init
c:\Users\Joao\Documents\Arduino\libraries\Adafruit_TinyUSB_Library\src\device\usbd.c: In function 'tud_deinit':
c:\Users\Joao\Documents\Arduino\libraries\Adafruit_TinyUSB_Library\src\device\usbd.c:455:26: error: 'usbd_class_driver_t' {aka 'const struct <anonymous>'} has no member named 'deinit'; did you mean 'init'?
     if(driver && driver->deinit) {
                          ^~~~~~
                          init
c:\Users\Joao\Documents\Arduino\libraries\Adafruit_TinyUSB_Library\src\device\usbd.c:457:15: error: 'usbd_class_driver_t' {aka 'const struct <anonymous>'} has no member named 'deinit'; did you mean 'init'?
       driver->deinit();
               ^~~~~~
               init
c:\Users\Joao\Documents\Arduino\libraries\Adafruit_TinyUSB_Library\src\device\usbd.c:457:7: error: called object is not a function or function pointer
       driver->deinit();
       ^~~~~~
c:\Users\Joao\Documents\Arduino\libraries\Adafruit_TinyUSB_Library\src\host\usbh.c:173:10: error: 'usbh_class_driver_t' {aka 'const struct <anonymous>'} has no member named 'name'
         .name       = DRIVER_NAME("CDC"),
          ^~~~
c:\Users\Joao\Documents\Arduino\libraries\Adafruit_TinyUSB_Library\src\host\usbh.c:175:10: error: 'usbh_class_driver_t' {aka 'const struct <anonymous>'} has no member named 'deinit'; did you mean 'init'?
         .deinit     = cdch_deinit,
          ^~~~~~
          init
c:\Users\Joao\Documents\Arduino\libraries\Adafruit_TinyUSB_Library\src\host\usbh.c:175:23: error: 'cdch_deinit' undeclared here (not in a function); did you mean 'cdch_init'?
         .deinit     = cdch_deinit,
                       ^~~~~~~~~~~
                       cdch_init
c:\Users\Joao\Documents\Arduino\libraries\Adafruit_TinyUSB_Library\src\host\usbh.c:185:10: error: 'usbh_class_driver_t' {aka 'const struct <anonymous>'} has no member named 'name'
         .name       = DRIVER_NAME("MSC"),
          ^~~~
c:\Users\Joao\Documents\Arduino\libraries\Adafruit_TinyUSB_Library\src\host\usbh.c:187:10: error: 'usbh_class_driver_t' {aka 'const struct <anonymous>'} has no member named 'deinit'; did you mean 'init'?
         .deinit     = msch_deinit,
          ^~~~~~
          init
c:\Users\Joao\Documents\Arduino\libraries\Adafruit_TinyUSB_Library\src\host\usbh.c:187:23: error: 'msch_deinit' undeclared here (not in a function); did you mean 'msch_init'?
         .deinit     = msch_deinit,
                       ^~~~~~~~~~~
                       msch_init
c:\Users\Joao\Documents\Arduino\libraries\Adafruit_TinyUSB_Library\src\host\usbh.c:197:10: error: 'usbh_class_driver_t' {aka 'const struct <anonymous>'} has no member named 'name'
         .name       = DRIVER_NAME("HID"),
          ^~~~
c:\Users\Joao\Documents\Arduino\libraries\Adafruit_TinyUSB_Library\src\host\usbh.c:199:10: error: 'usbh_class_driver_t' {aka 'const struct <anonymous>'} has no member named 'deinit'; did you mean 'init'?
         .deinit     = hidh_deinit,
          ^~~~~~
          init
c:\Users\Joao\Documents\Arduino\libraries\Adafruit_TinyUSB_Library\src\host\usbh.c:199:23: error: 'hidh_deinit' undeclared here (not in a function); did you mean 'hcd_deinit'?
         .deinit     = hidh_deinit,
                       ^~~~~~~~~~~
                       hcd_deinit
c:\Users\Joao\Documents\Arduino\libraries\Adafruit_TinyUSB_Library\src\host\usbh.c:209:10: error: 'usbh_class_driver_t' {aka 'const struct <anonymous>'} has no member named 'name'
         .name       = DRIVER_NAME("HUB"),
          ^~~~
c:\Users\Joao\Documents\Arduino\libraries\Adafruit_TinyUSB_Library\src\host\usbh.c:211:10: error: 'usbh_class_driver_t' {aka 'const struct <anonymous>'} has no member named 'deinit'; did you mean 'init'?
         .deinit     = hub_deinit,
          ^~~~~~
          init
c:\Users\Joao\Documents\Arduino\libraries\Adafruit_TinyUSB_Library\src\host\usbh.c: In function 'tuh_deinit':
c:\Users\Joao\Documents\Arduino\libraries\Adafruit_TinyUSB_Library\src\host\usbh.c:459:29: error: 'usbh_class_driver_t' {aka 'const struct <anonymous>'} has no member named 'deinit'; did you mean 'init'?
       if (driver && driver->deinit) {
                             ^~~~~~
                             init
c:\Users\Joao\Documents\Arduino\libraries\Adafruit_TinyUSB_Library\src\host\usbh.c:461:17: error: 'usbh_class_driver_t' {aka 'const struct <anonymous>'} has no member named 'deinit'; did you mean 'init'?
         driver->deinit();
                 ^~~~~~
                 init
c:\Users\Joao\Documents\Arduino\libraries\Adafruit_TinyUSB_Library\src\host\usbh.c:461:9: error: called object is not a function or function pointer
         driver->deinit();
         ^~~~~~

`

### What happened ?

It doesn't compile for ESP32S3. Didn't test other boards yet. error attached above

### How to reproduce ?

Compile sketch

**Comment by jhsa** [comment]
It doesn't compile for the ESP32S2 also. Just checked.

**Comment by esp32beans** [comment]
Reverting to Adafruit_TinyUSB verion 3.1.3 eliminates the compiler errors.

Board: ESP32S3 Dev Module
Arduino IDE 1.8.19
arduino-esp32 BSP 2.0.17

**Comment by jhsa** [comment]
> Reverting to Adafruit_TinyUSB verion 3.1.3 eliminates the compiler errors.
> 
> Board: ESP32S3 Dev Module Arduino IDE 1.8.19 arduino-esp32 BSP 2.0.17

Thank you. So it is really a bug.
I will try reverting..

**Comment by jhsa** [comment]
3.1.3 compiles..

**Comment by jhaimerl1** [comment]
I can't get the example to compile with any version after 2.40 for a Nano ESP32...

**Comment by DonWT** [comment]
Still fails (miserably and resoundingly) to compile with version 3.3.3

**Comment by jhaimerl1** [comment]
Too bad… using Teensy right now

**Comment by DonWT** [comment]
I am using an ESP32 because I want to use both USB and BLE midi.  I will
continue with 2.40 for now although Espressif are readying their own
version of the Tiny USB library.

I think that this looks really bad for Adafruit as this is an essential
library for ESP32 S3 boards.

I might just take a copy of the 2.40 source and remove the Tiny USB library
from my IDE.

**Comment by hathach** [comment]
not reproducible with arduino-esp32 v3.2.0 and tinyusb 3.5.0, please update your setup and try again
