### ISSUE TITLE
More supported boards, especially Teensy 4.0 [Feature]

### ISSUE THREAD

**Issue by iosonoisaac** [adafruit/Adafruit_TinyUSB_Arduino#63]
This library is a game changer! I'd love to use this library for other projects that utilize other development boards.

Specifically, I'd love to use the SD Card Mass Storage Device feature with a **Teensy 4.0**.

It looks like hathach's original library seems to support Teensy 4.0 (https://github.com/hathach/tinyusb/blob/master/docs/boards.md)

But I can't seem to get any of the example files from Adafruit's TinyUSB Library to work on a Teensy 4.0.

Am I missing something? Is there something I can do to read/write on an SD Card in a Teensy 4.0 via the USB port as a Mass Storage Device like you can with Adafruit's M0 & M4 dev boards?

Is support for Teensy 4.0 with this library something that may be possible in the near future?

Thanks!!!

**Comment by tannewt** [comment]
@iosonoisaac What happens when you try to use the examples? Do they compile?

**Comment by iosonoisaac** [comment]
When I select the board as a Teensy, I get this error when attempting to compile the "msc_sd" example:

```
.../Documents/Arduino/libraries/Adafruit_TinyUSB_Library/src/Adafruit_USBD_HID.h:28:35: fatal error: Adafruit_TinyUSB_Core.h: No such file or directory
compilation terminated.
Error compiling for board Teensy 4.0.
```

This error is not given when I use one of Adafruit's supported boards.

I'm guessing this is partly because when the board is selected as a Teensy (or anything other than Adafruit's supported boards), I don't have the option to set the "USB Stack" to TinyUSB:
<img width="294" alt="Teensy 4.0 Board" src="https://user-images.githubusercontent.com/42870112/81732818-e1ca3080-9445-11ea-950b-9d4f23c42c2c.png">


However, that is an option when I use the ItsyBitsy M4 for example:
<img width="452" alt="ItsyBitsy M4 Board" src="https://user-images.githubusercontent.com/42870112/81732843-ebec2f00-9445-11ea-94c5-845879c4198b.png">

None of the examples in Adafruit's TinyUSB library compile with Teensy 4.0, but I'm specifically trying "msc_sd."

**Comment by hathach** [comment]
@iosonoisaac thanks for your kind words, unfortunately TinyUSB requires the core BSP to support (port) it.  It is not as simple as other peripherals such as I2C. Since most the core will use and setup using its USB stack for CDC before setup() is run.  

For BSP core to support TinyUSB  https://github.com/adafruit/Adafruit_TinyUSB_ArduinoCore must be added and ported to the platform. You will need to ask Teensy BSP maintaining team to port it first.

In the future, I will try to see if we could make it easier to support on new platform by moving most parts of the Core to the Lib, more or less it still needs BSP changes to adopt the library.

**Comment by iosonoisaac** [comment]
@hathach  thanks for taking the time to respond and give that info. I'll see if anyone from the BSP maintaining team has time to look into it.

**Comment by hathach** [comment]
@iosonoisaac here is how samd and nrf implement the core support
- https://github.com/adafruit/ArduinoCore-samd/tree/master/cores/arduino/TinyUSB
- https://github.com/adafruit/Adafruit_nRF52_Arduino/tree/master/cores/nRF5/TinyUSB

Note it is still subject to change though, since it is hard to get the big picture when I added the initial port.

**Comment by hathach** [comment]
closed since there is nothing we could do until core team from Teensy support it first.
